'use strict';
const Cloud=(()=>{
 const metaKey='bhob-cloud-records-v1',ownerKey='bhob-cloud-owner-v1';
 let client=null,user=null,records={},pending=new Set(),timer,busy=false,again=false,last=0,status='未登录 · 仅本机保存',snapshot=null,ready=false;
 const recordKey=(kind,id)=>JSON.stringify([kind,id]);
 const writeLocal=()=>{try{localStorage.setItem(key,JSON.stringify(state));localStorage.setItem(metaKey,JSON.stringify({records,pending:[...pending]}));return true}catch{saveOK=false;return false}};
 function entries(s){const out={};for(const [kind,list] of [['completed',s.completed],['bookmark',s.bookmarks]])for(const id of list||[])out[recordKey(kind,id)]={kind,item_id:id,value:true};for(const [kind,obj]of [['answer',s.answers],['note',s.notes],['setting',{mode:s.mode,year:s.year}]])for(const [id,value]of Object.entries(obj||{}))out[recordKey(kind,id)]={kind,item_id:id,value};return out}
 function capture(initial=false){const next=entries(state),old=snapshot||{};for(const k of new Set([...Object.keys(old),...Object.keys(next)])){if(!initial&&JSON.stringify(old[k])===JSON.stringify(next[k]))continue;if(initial&&records[k])continue;const r=next[k]||old[k];if(!r)continue;records[k]={...r,deleted:!next[k],changed_at:initial?1:Math.max(Date.now(),(records[k]?.changed_at||0)+1)};pending.add(k)}snapshot=next;}
 function apply(){const next=blank();for(const r of Object.values(records)){if(r.deleted)continue;const {kind,item_id:id,value}=r;if(kind==='completed')next.completed.push(id);if(kind==='bookmark')next.bookmarks.push(id);if(kind==='answer')next.answers[id]=value;if(kind==='note')next.notes[id]=value;if(kind==='setting'&&['mode','year'].includes(id))next[id]=value}state=next;snapshot=entries(state);writeLocal()}
 function statusUI(){const e=document.querySelector('#cloud-status');if(e)e.textContent=status}
 function changed(){capture();const ok=writeLocal();status=user?'待同步': '未登录 · 仅本机保存';statusUI();if(user){clearTimeout(timer);timer=setTimeout(sync,900)}return ok}
 async function sync(){if(!client||!user||!ready)return;if(busy){again=true;return}busy=true;const uid=user.id;status='正在同步…';statusUI();try{
  if(!navigator.onLine)throw Error('离线');
  const batch=[...pending].map(k=>({...records[k]}));
  if(batch.length){const {error}=await client.rpc('bhob_merge_learning',{records:batch});if(error)throw error}
  const all=[];for(let offset=0;;offset+=500){const {data,error}=await client.from('bhob_learning_records').select('kind,item_id,value,deleted,changed_at').eq('user_id',uid).order('kind').order('item_id').range(offset,offset+499);if(error)throw error;all.push(...data);if(data.length<500)break}
  if(user?.id!==uid)return;
  for(const remote of all){const k=recordKey(remote.kind,remote.item_id);if(!records[k]||Number(remote.changed_at)>records[k].changed_at)records[k]=remote}
  for(const sent of batch){const k=recordKey(sent.kind,sent.item_id);if(records[k]?.changed_at===sent.changed_at)pending.delete(k);else if(all.some(r=>recordKey(r.kind,r.item_id)===k&&r.changed_at===records[k]?.changed_at))pending.delete(k)}
  apply();last=Date.now();status=pending.size?'待同步':'已同步 · '+new Date(last).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});if(pending.size)again=true;render();
 }catch(e){status=navigator.onLine?'同步失败 · 可重试':'离线 · 待联网同步';statusUI()}finally{busy=false;if(again){again=false;clearTimeout(timer);timer=setTimeout(sync,900)}}}
 async function accept(session){const next=session?.user||null;if(user?.id===next?.id)return;ready=false;user=next;if(!user){status='未登录 · 仅本机保存';render();return}const previous=localStorage.getItem(ownerKey);if(previous&&previous!==user.id){records={};pending=new Set();state=blank();snapshot=entries(state);writeLocal()}localStorage.setItem(ownerKey,user.id);ready=true;status='待同步';render();sync()}
 function panel(){if(!client)return '<section class="card section"><h2>账号与云端同步</h2><p>云端连接未加载，请联网刷新；本机记录仍可使用。</p></section>';return `<section class="card section"><h2>账号与云端同步</h2><p id="cloud-status" role="status">${esc(status)}</p>${user?`<p>${esc(user.email||'已登录')}</p><div class="lesson-actions"><button id="cloud-sync">立即同步</button><button id="cloud-signout">退出登录</button></div><p class="muted">收藏、进度、答题记录和笔记按账号保存。换设备请登录同一邮箱；离线操作会在联网后补传。</p>`:`<form id="cloud-login"><label>邮箱<input id="cloud-email" type="email" required autocomplete="email" placeholder="你的邮箱"></label><button type="submit" class="button">发送登录邮件</button></form><details class="section"><summary>粘贴邮件登录链接</summary><p class="muted">复制登录邮件按钮的完整链接，粘贴到这里完成登录。链接仅用于本机验证，请勿转发。</p><form id="cloud-verify"><label>登录链接<input id="cloud-token" type="url" required autocomplete="off"></label><button class="button" type="submit">验证并登录</button></form></details><p class="muted">首次登录会合并此设备已有记录。当前邮件服务仅向项目成员邮箱发送；其他邮箱需要配置邮件服务。</p>`}</section>`}
 function bind(){document.querySelector('#cloud-sync')?.addEventListener('click',sync);document.querySelector('#cloud-signout')?.addEventListener('click',async()=>{if(pending.size){await sync();if(pending.size){toast('仍有未同步记录，请联网同步后退出');return}}const {error}=await client.auth.signOut();if(error){toast('退出失败，请重试');return}user=null;ready=false;state=blank();records={};pending=new Set();snapshot=entries(state);writeLocal();localStorage.removeItem(ownerKey);status='未登录 · 仅本机保存';render()});document.querySelector('#cloud-login')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;const {error}=await client.auth.signInWithOtp({email:document.querySelector('#cloud-email').value.trim(),options:{emailRedirectTo:location.origin+location.pathname+'#me'}});b.disabled=false;toast(error?'邮件发送失败：'+error.message:'请查看邮箱；可复制登录链接在这里验证')});document.querySelector('#cloud-verify')?.addEventListener('submit',async e=>{e.preventDefault();try{const u=new URL(document.querySelector('#cloud-token').value.trim());if(u.origin!=='https://ncmbuhcnqvejzpzxklkm.supabase.co'||u.pathname!=='/auth/v1/verify')throw Error('请粘贴本项目的邮件登录链接');const token_hash=u.searchParams.get('token'),type=u.searchParams.get('type');if(!token_hash||!['magiclink','signup','email'].includes(type))throw Error('链接不完整');const {error}=await client.auth.verifyOtp({token_hash,type});if(error)throw error;document.querySelector('#cloud-token')?.form.reset();toast('登录成功，正在合并记录')}catch(err){toast('验证失败：'+err.message)}})}
 async function init(){try{const stored=JSON.parse(localStorage.getItem(metaKey)||'{}');records=stored.records||{};pending=new Set(stored.pending||[]);capture(true);writeLocal();if(!window.BHOBSupabase)return;client=window.BHOBSupabase.createClient('https://ncmbuhcnqvejzpzxklkm.supabase.co','sb_publishable_SH8N21d8XOAl_13rLC4DOA_lqBrvOUm');client.auth.onAuthStateChange((event,session)=>{setTimeout(()=>accept(session),0)});const {data,error}=await client.auth.getSession();if(error)throw error;await accept(data.session);if(!data.session){status='未登录 · 仅本机保存';render()}}catch{status='云端连接失败 · 本机记录保留';statusUI()}}
 window.addEventListener('online',sync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});window.addEventListener('focus',()=>{if(Date.now()-last>15000)sync()});
 return {init,changed,sync,panel,bind};
})();
