'use strict';
const hubPaths={papers:'data/research/papers.json',pipelines:'data/drugs/pipelines.json',preclinical:'data/drugs/preclinical.json',modalities:'data/drugs/modalities.json',clinical:'data/drugs/clinical.json',tools:'data/library/tools.json'};
let H=Object.fromEntries(Object.keys(hubPaths).map(k=>[k,[]])),hubErrors=[],drugFilters={stage:'',modality:'',area:'',status:''};
async function loadHub(){const results=await Promise.allSettled(Object.entries(hubPaths).map(async([k,path])=>{const r=await jsonFile(path+'?v=3.0.0');if(!Array.isArray(r.data))throw Error('无效数据');H[k]=r.data;return k}));hubErrors=results.flatMap((r,i)=>r.status==='rejected'?[Object.keys(hubPaths)[i]]:[])}
const hubCard=(page,x,kind='')=>`<a class="card linkcard" href="#${page}/${encodeURIComponent(x.id)}">${badge(kind||x.topic||x.area||'知识卡')}${x.stage?badge(x.stage,'gold'):''}<h3>${esc(x.title)}</h3><p class="muted">${esc(x.summary||x.indication||'')}</p>${x.date?`<small>论文发表 ${esc(x.date)}</small>`:''}</a>`;
const hubNav=()=>`<div class="subnav hubnav">${[['drugs','管线'],['preclinical','临床前'],['modalities','药物形式'],['targets','靶点'],['companies','公司'],['clinical','临床阅读'],['deals','交易'],['failures','失败复盘'],['calendar','催化剂']].map(([p,t])=>`<a class="${route()[0]===p?'active':''}" href="#${p}">${t}</a>`).join('')}</div>`;
const hubNotice=()=>hubErrors.length?`<div class="notice error">部分知识库加载失败，现有学习记录保留。<button id="retryhub">重试加载</button></div>`:'';
function allPapers(){const seen=new Map([...H.papers,...(D.neuro.archivedPapers||[])].map(x=>[x.id,x]));for(const b of [...(D.neuro.items||[])].reverse())for(const p of b.papers||[])if(p.id&&p.title&&Array.isArray(p.sections)&&Array.isArray(p.sources))seen.set(p.id,p);return [...seen.values()].sort((a,b)=>String(b.date||'').localeCompare(a.date||''))}
function hubHome(){const next=D.lessons.find(x=>!state.completed.includes(x.id))||D.lessons[0],papers=allPapers();return `<div class="home-date">${esc(today())} · 研究与商业，每天连起来</div><section class="hero"><div class="eyebrow">BIOFINANCE INTELLIGENCE</div><h1>从科学发现，<br>走到自己的判断。</h1><p class="muted">文献精读 · 创新药证据 · 金融100课<br>读来源，理解意义，再写下你的观点。</p><a class="button" href="#lesson/${next.id}">继续学习：${esc(next.title)} →</a></section>${hubNotice()}<div class="grid3 section"><a class="card stat" href="#research"><div class="big">${papers.length}</div><small>文献库</small></a><a class="card stat" href="#drugs"><div class="big">${H.pipelines.length}</div><small>试验快照</small></a><a class="card stat" href="#courses"><div class="big">${state.completed.filter(x=>D.lessons.some(l=>l.id===x)).length}<small> / ${D.lessons.length}</small></div><small>已完成课程</small></a></div><section class="section"><div class="row"><h2>基础研究 · 精选精读</h2><a href="#research">文献库 →</a></div><p class="muted">以下为已核查精选，按论文发表日期排序；每日新增以定时任务实际发布为准。</p><div class="grid">${papers.slice(0,3).map(x=>hubCard('paper',x)).join('')||empty('暂未加载文献')}</div></section><section class="section"><div class="row"><h2>今日信息入口</h2><a href="#briefs">历史与刷新 →</a></div><div class="grid">${feedCards('neuro')}${feedCards('finance')}</div></section><section class="section"><h2>探索创新药</h2><div class="grid">${[['drugs','管线数据库','按阶段、药物形式、适应症领域和状态组合筛选。'],['preclinical','临床前研究','把机制线索与候选药物开发证据分开看。'],['clinical','临床数据阅读','读懂分母、对照、终点与安全性。'],['deals','交易与行业','通过真实历史案例理解授权与并购。']].map(([p,t,s])=>hubCard(p,{id:'',title:t,summary:s},'探索')).join('')}</div></section><div class="subnav"><a href="#finance">金融学院</a><a href="#calendar">催化剂日历</a><a href="#library">收藏与判断</a><a href="#terms">中英术语</a></div><p class="footer">管线为公开登记试验快照，非全球全量数据库。登录后学习记录自动同步到云端；离线操作会暂存。</p>`}
function researchPage(){const topics=[...new Set(allPapers().map(p=>p.topic||'其他'))],items=allPapers().filter(x=>(filter==='all'||x.topic===filter)&&JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));return `${pageHeading('研究 · 不止读摘要','从研究问题、方法和发现，读到意义、局限与转化边界。')}${hubNotice()}<div class="toolbar"><input id="search" aria-label="搜索文献" placeholder="搜索论文、靶点、研究方法…" value="${esc(search)}"></div><div class="chips">${['all',...topics].map(t=>`<button data-filter="${esc(t)}" class="${filter===t?'active':''}">${t==='all'?'全部':esc(t)}</button>`).join('')}</div><div class="grid">${items.map(x=>hubCard('paper',x)).join('')||empty('没有符合条件的文献')}</div><section class="section"><h2>每日研究简报归档</h2><div class="grid">${feedCards('neuro',90)}</div></section><section class="section"><h2>专题深读</h2>${H.tools.filter(x=>x.id.startsWith('weekly')).map(x=>hubCard('tool',x,'专题')).join('')}</section>`}
function entityPage(type,id){const data=type==='paper'?allPapers():type==='drug'?H.pipelines:H[{preclinical:'preclinical',modality:'modalities',clinical:'clinical',tool:'tools'}[type]]||[],x=data.find(x=>x.id===id);if(!x)return empty('未找到内容，请返回栏目或重新加载');const back={paper:'research',drug:'drugs',preclinical:'preclinical',modality:'modalities',clinical:'clinical',tool:'library'}[type];let sections=x.sections||[];if(type==='drug')sections=[{heading:'试验与阶段',body:`${x.trialTitle}\n${x.id} · ${x.stage}\n招募状态：${statusLabel(x.status)}\n申办方：${x.company}\n适应症：${x.indication}\n登记更新：${x.registryUpdated} · 核查：${x.checked}`},{heading:'登记研究说明 · 原文',body:x.summary},{heading:'主要终点 · 登记原文',body:x.endpoints.join('\n')},{heading:'证据阅读重点 · 编辑提示',body:x.risks},{heading:'阶段口径',body:x.note},...(x.whyStopped?[{heading:'终止原因 · 登记原文',body:x.whyStopped}]:[])];return `<article class="article"><a class="back" href="#${back}">← 返回栏目</a><div>${badge(x.topic||x.modality||'知识卡')}${x.stage?badge(x.stage,'gold'):''}</div><h1>${esc(x.title)}</h1>${x.date?`<p class="muted">发表：${esc(x.date)} · 核查：${esc(x.checked||'见来源')}</p>`:''}${bookmark(x.id)}${type!=='drug'?`<div class="block plain"><h2>一句话</h2><p>${esc(x.summary)}</p></div>`:''}${sections.map(s=>`<div class="block"><h2>${esc(s.heading)}</h2><p class="bodytext">${esc(s.body)}</p></div>`).join('')}${x.target?`<div class="subnav"><a href="#targets/${encodeURIComponent(x.target)}">靶点：${esc(x.target)}</a>${type==='drug'?`<a href="#companies/${encodeURIComponent(x.company)}">公司：${esc(x.company)}</a>`:''}</div>`:''}${x.paper?`<a class="button secondary" href="#paper/${x.paper}">关联原始研究 →</a>`:''}${x.related?`<div class="subnav">${x.related.map(id=>`<a href="#paper/${id}">${esc(allPapers().find(p=>p.id===id)?.title||id)}</a>`).join('')}</div>`:''}${x.course?`<a href="#lesson/${x.course}">对应金融课 →</a>`:''}<div class="block"><h2>我的判断与复盘</h2><p class="muted">支持证据 / 反方论点 / 最大不确定性 / 改变观点的条件 / 后续结果</p><textarea rows="6" data-note="${esc(x.id)}" aria-label="我的判断笔记" placeholder="写下判断，再回来检验…">${esc(state.notes[x.id]||'')}</textarea></div>${sources(x.sources)}</article>`}
const statusLabel=s=>({RECRUITING:'招募中',ACTIVE_NOT_RECRUITING:'进行中，停止招募',COMPLETED:'已完成',TERMINATED:'已终止',WITHDRAWN:'撤回',SUSPENDED:'暂停',NOT_YET_RECRUITING:'尚未招募',ENROLLING_BY_INVITATION:'邀请入组',UNKNOWN:'未知'}[s]||s);
function drugPage(){let items=H.pipelines.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())&&Object.entries(drugFilters).every(([k,v])=>!v||x[k]===v));return `${pageHeading('创新药 · 从资产到证据','涵盖肿瘤、代谢、心血管、自免、感染、肾脏、眼科、罕见病与CNS。')}${hubNav()}${hubNotice()}<p class="notice">当前 ${H.pipelines.length} 项登记试验快照，核查于2026-10-06。阶段对应具体试验，不代表药物全球最高阶段或监管获批状态；临床前研究请切换专栏。</p><div class="toolbar"><input id="search" aria-label="搜索药物" placeholder="搜索药物、靶点、公司或适应症…" value="${esc(search)}"></div><div class="filter-grid">${[['stage','试验阶段'],['modality','药物形式'],['area','疾病领域'],['status','试验状态']].map(([k,label])=>`<label>${label}<select data-drug-filter="${k}"><option value="">全部</option>${[...new Set(H.pipelines.map(x=>x[k]))].sort().map(v=>`<option value="${esc(v)}" ${drugFilters[k]===v?'selected':''}>${esc(k==='status'?statusLabel(v):v)}</option>`).join('')}</select></label>`).join('')}</div><div class="row section"><small>${items.length} 项符合条件</small><button id="resetdrugs">重置筛选</button></div><div class="grid">${items.map(x=>`<a class="card linkcard" href="#drug/${x.id}">${badge(x.modality)}${badge(x.stage,'gold')}<h3>${esc(x.title)}</h3><p class="muted">${esc(x.target)} · ${esc(x.company)}</p><p>${esc(x.indication)}</p><small>${esc(statusLabel(x.status))} · 登记更新 ${esc(x.registryUpdated)}</small></a>`).join('')||empty('没有匹配试验，请调整筛选')}</div>`}
function simpleHub(type,title,sub,page){return `${pageHeading(title,sub)}${['preclinical','modalities','clinical'].includes(type)?hubNav():''}${hubNotice()}<div class="toolbar"><input id="search" aria-label="搜索栏目" placeholder="搜索内容…" value="${esc(search)}"></div><div class="grid">${H[type].filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())).map(x=>hubCard(page,x)).join('')||empty('暂无符合条件的内容')}</div>`}
function connectedPage(type,id){const field=type==='targets'?'target':'company',items=type==='targets'?[...H.pipelines,...H.preclinical,...allPapers()]:H.pipelines,values=[...new Set(items.map(x=>x[field]).filter(Boolean))].sort();if(!id)return `${pageHeading(type==='targets'?'靶点索引':'公司索引','由已收录证据建立关联，不把缺失信息猜成事实。')}${hubNav()}<div class="toolbar"><input id="search" aria-label="搜索索引" placeholder="搜索…" value="${esc(search)}"></div><div class="grid">${values.filter(v=>v.toLowerCase().includes(search.toLowerCase())).map(v=>`<a class="card linkcard" href="#${type}/${encodeURIComponent(v)}"><h3>${esc(v)}</h3><p class="muted">${items.filter(x=>x[field]===v).length} 项关联证据 →</p></a>`).join('')}</div>`;return `${pageHeading(id,type==='targets'?'生物学、人体证据、成药性、竞争和安全性：从关联原文逐项核查。':'这里的公司名称来自试验申办方字段；不等于完整资产权属或全球公司管线。')}${hubNav()}<div class="grid">${items.filter(x=>x[field]===id).map(x=>hubCard(H.pipelines.includes(x)?'drug':H.preclinical.includes(x)?'preclinical':'paper',x)).join('')||empty('尚无关联内容')}</div><a class="button secondary section" href="#lesson/${type==='targets'?'l21':'l94'}">学习如何评估 →</a>`}
function financeHub(){return `${pageHeading('金融学院 · 100课与实战','原30课保留为入门主线；31—100课深化会计、市场、估值、融资、医药商业与临床判断。')}<div class="grid">${[['courses','金融100课','100节完整知识卡、教学算例和应用练习。'],['cases','案例库','真实历史交易与明确标注的模拟练习。'],['cfa','CFA Level I','主题知识卡、原创练习和错题复习。'],['calc','金融计算器','EV、NPV、IRR、稀释、rNPV和患者漏斗。'],['terms','中英术语','从一句话解释建立金融语言。']].map(([p,t,s])=>hubCard(p,{id:'',title:t,summary:s},'学习')).join('')}</div>`}
function dealsHub(){return `${pageHeading('交易与行业','按实际权益、首付款、条件里程碑和时间口径读交易。')}${hubNav()}<div class="grid">${D.cases.filter(x=>x.kind==='真实历史案例').map(x=>hubCard('case',{...x,summary:x.lesson},x.category)).join('')}</div><section class="section"><h2>医药金融简报</h2><div class="grid">${feedCards('finance',90)}</div></section><a class="button secondary" href="#lesson/l95">交易可比工作表 →</a>`}
function calendarHub(){const items=H.pipelines.filter(x=>x.completion?.date).sort((a,b)=>a.completion.date.localeCompare(b.completion.date));return `${pageHeading('催化剂日历','注册主要完成时间用于规划关注，不等于结果发布日期。')}<p class="notice">日期可能延后或已过期；以下为核查时登记快照。结果读出、申报或获批时间需独立来源确认。</p>${hubNav()}<div class="grid">${items.map(x=>`<a class="card linkcard" href="#drug/${x.id}">${badge(x.completion.date)}${badge(x.completion.type==='ACTUAL'?'实际完成':'预计完成','gold')}<h3>${esc(x.title)}</h3><p>${esc(statusLabel(x.status))}</p><small>主要完成时间 · ${esc(x.id)}</small></a>`).join('')||empty('暂无已登记时间')}</div>`}
function libraryHub(){const saved=state.bookmarks.map(id=>savedLink(id)).filter(Boolean);return `${pageHeading('我的知识库','登录后收藏、笔记与学习记录按账号跨设备同步。')}${Cloud.panel()}<div class="subnav"><a href="#me">学习记录与备份</a><a href="#terms">术语</a><a href="#failures">失败复盘</a></div><section class="section"><h2>收藏与待读</h2><div class="card">${saved.map(x=>`<div class="course-row"><a href="${x.url}">${esc(x.title)}</a></div>`).join('')||empty('打开文献、药物或课程，点击收藏')}</div></section><section class="section"><h2>我的判断记录</h2><div class="card">${Object.entries(state.notes).filter(([id,v])=>v.trim()).map(([id,v])=>{const x=savedLink(id);return x?`<div class="course-row"><div><a href="${x.url}">${esc(x.title)}</a><p class="muted">${esc(v.slice(0,120))}</p></div></div>`:''}).join('')||empty('在内容详情页写下判断，它会自动保存在这里')}</div></section><div class="grid section">${H.tools.map(x=>hubCard('tool',x)).join('')}</div>`}
function failureHub(){return `${pageHeading('失败复盘','先看登记原因，再区分靶点、分子、试验执行和商业因素。')}${hubNav()}<div class="grid">${H.pipelines.filter(x=>['TERMINATED','WITHDRAWN','SUSPENDED'].includes(x.status)).map(x=>hubCard('drug',x,statusLabel(x.status))).join('')}</div>${H.tools.filter(x=>x.id.startsWith('failure')).map(x=>hubCard('tool',x,'阅读方法')).join('')}`}
function mergePipelineFeeds(){for(const x of [...(D.finance.archivedPipelines||[]),...[...(D.finance.items||[])].reverse().flatMap(b=>b.pipelineUpdates||[])]){if(!x.id||!x.title||!Array.isArray(x.endpoints)||!Array.isArray(x.sources))continue;const index=H.pipelines.findIndex(v=>v.id===x.id);if(index<0)H.pipelines.push(x);else if(String(x.checked||'')>=String(H.pipelines[index].checked||''))H.pipelines[index]=x}}
function bindHub(){document.querySelectorAll('[data-drug-filter]').forEach(e=>e.onchange=()=>{drugFilters[e.dataset.drugFilter]=e.value;render()});$('#resetdrugs')?.addEventListener('click',()=>{drugFilters={stage:'',modality:'',area:'',status:''};search='';render()});$('#retryhub')?.addEventListener('click',async()=>{await loadHub();render()})}
function hubSaved(id){for(const [type,data] of [['paper',allPapers()],['drug',H.pipelines],['preclinical',H.preclinical],['modality',H.modalities],['clinical',H.clinical],['tool',H.tools]]){const x=data.find(x=>x.id===id);if(x)return {title:x.title,url:'#'+type+'/'+encodeURIComponent(id)}}return null}
// Structured industry records are maintained by the daily finance publisher.
function industryRecords(kind){const map=new Map();for(const x of D.finance['archived'+kind[0].toUpperCase()+kind.slice(1)]||[])if(x.id)map.set(x.id,x);for(const b of [...(D.finance.items||[])].reverse())for(const x of b[kind]||[])if(x.id)map.set(x.id,x);return [...map.values()]}
function industryDetail(kind,id){const x=industryRecords(kind).find(x=>x.id===id);if(!x)return empty('暂无此条记录');return `<article class="article"><a href="#${kind==='catalysts'?'calendar':kind}">← 返回</a><h1>${esc(x.title)}</h1><p class="muted">事件：${esc(x.date||'未确认')} · 核查：${esc(x.checked||'未确认')}</p>${bookmark(x.id)}<div class="block plain"><p>${esc(x.summary)}</p></div>${(x.sections||[]).map(s=>`<div class="block"><h2>${esc(s.heading)}</h2><p class="bodytext">${esc(s.body)}</p></div>`).join('')}<div class="block"><h2>我的判断</h2><textarea data-note="${esc(x.id)}" rows="5">${esc(state.notes[x.id]||'')}</textarea></div>${sources(x.sources)}</article>`}
const originalConnected=connectedPage;
connectedPage=function(type,id){const records=industryRecords(type),x=records.find(x=>x.id===id||x.title===id);if(x)return industryDetail(type,x.id)+originalConnected(type,x.title);return originalConnected(type,id)+(id?'':`<section class="section"><h2>已核查动态档案</h2><div class="grid">${records.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())).map(x=>hubCard(type,x,'动态档案')).join('')||empty('等待首次定时更新发布')}</div></section>`)};
const originalDeals=dealsHub;dealsHub=function(){return `<section class="section"><h2>最新交易</h2><div class="grid">${industryRecords('deals').sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>hubCard('deal',x,'公开交易')).join('')||empty('等待首次定时更新；历史教学案例见下方')}</div></section>`+originalDeals()};
const originalCalendar=calendarHub;calendarHub=function(){return `<section class="section"><h2>读出、申报与监管事件</h2><div class="grid">${industryRecords('catalysts').sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(x=>hubCard('catalyst',x,x.status||'预计')).join('')||empty('等待核实的事件日历；登记完成日期见下方')}</div></section>`+originalCalendar()};
const originalHubSaved=hubSaved;hubSaved=function(id){for(const [kind,page] of [['companies','companies'],['targets','targets'],['deals','deal'],['catalysts','catalyst']]){const x=industryRecords(kind).find(x=>x.id===id);if(x)return {title:x.title,url:'#'+page+'/'+encodeURIComponent(id)}}return originalHubSaved(id)};
const originalHome=hubHome;hubHome=function(){const s=D.finance.syncStatus;return originalHome()+`<div class="notice">行业数据库自动核查：${s?esc(s.checkedAt||'未记录')+' · '+esc(s.summary||s.status||'见简报'):'等待首次每日核查。每天北京时间07:00启动，完成发布后更新。'}</div>`};
